# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Project/ZynqLearning/0_GPIO_AXI/0_GPIO_AXI.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/ZynqLearning/0_GPIO_AXI/0_GPIO_AXI.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/Project/ZynqLearning/0_GPIO_AXI/0_GPIO_AXI.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0.xci
# IP: The module: 'system_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Project/ZynqLearning/0_GPIO_AXI/0_GPIO_AXI.gen/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
