set_property SRC_FILE_INFO {cfile:E:/Project/ZynqLearning/0_GPIO_AXI/0_GPIO_AXI.srcs/constrs_1/new/system.xdc rfile:../../../0_GPIO_AXI.srcs/constrs_1/new/system.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H12 [get_ports {gpio_rtl_0_tri_io[1]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H13 [get_ports {gpio_rtl_0_tri_io[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN F13 [get_ports {gpio_rtl_1_tri_io[1]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN E13 [get_ports {gpio_rtl_1_tri_io[0]}]
