######################################################################
#
# File name : waterfall_light_tb_wave.do
# Created on: Tue Apr 11 16:09:09 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
