######################################################################
#
# File name : waterfall_light_compile.do
# Created on: Tue Apr 11 16:00:13 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
D:\\IntelFPGA\\modeltech64_10.4\\win64\\vlib modelsim_lib/work
D:\\IntelFPGA\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim

D:\\IntelFPGA\\modeltech64_10.4\\win64\\vlib modelsim_lib/msim/xil_defaultlib

D:\\IntelFPGA\\modeltech64_10.4\\win64\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

D:\\IntelFPGA\\modeltech64_10.4\\win64\\vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../0_WATERFALL_LIGHT.srcs/sources_1/new/waterfall_light.v" \


# compile glbl module
D:\\IntelFPGA\\modeltech64_10.4\\win64\\vlog -work xil_defaultlib "glbl.v"

quit -force

