######################################################################
#
# File name : waterfall_light_simulate.do
# Created on: Tue Apr 11 16:00:17 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.waterfall_light xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {waterfall_light_wave.do}

view wave
view structure
view signals

do {waterfall_light.udo}

run 1000ns
